# This file defines the services, networks, and volumes for our multi-container Docker application.
services:
  # The OpenHands service provides the sandboxed execution environment for our agents.
  openhands:
    image: ghcr.io/all-hands-ai/openhands:0.14.2
    container_name: openhands_runtime
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./workspace:/opt/workspace_base
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:0.14.2-nikolaik
      - SANDBOX_USER_ID=${SANDBOX_USER_ID:-1000}
      - WORKSPACE_MOUNT_PATH=/opt/workspace_base
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # The orchestrator service runs our main LangGraph Python application.
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: langgraph_orchestrator
    # The env_file directive tells Docker Compose to load environment variables from the .env file.
    env_file:
      - .env
    volumes:
      # Mount the entire project directory into the container for easy access to all files.
      - .:/workspaces/agentic-dev-platform
    depends_on:
      - openhands
    # Keep the container running in the background.
    tty: true
    stdin_open: true

volumes:
  workspace:

